services:
  - type: web
    name: audio-to-text-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://transcriber_db_u601_user:VXBo7qGShdSWSrQ32q6EXKcngE9ZAYTm@dpg-cve1fi56l47c73a9tot0-a/transcriber_db_u601
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_VERIFICATION_SECRET
        generateValue: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USERNAME
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: FRONTEND_URL
        value: https://audio-to-text-frontend.onrender.com

  - type: web
    name: audio-to-text-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run serve
    envVars:
      - key: REACT_APP_API_URL
        value: https://audio-to-text-backend.onrender.com 